<?php
return [
    'dodge_2000' => [
        [['callback_data' => 'avenger_dodge_1994', 'text' => 'avenger(I)']],
        [['callback_data' => 'caravan_dodge_1995', 'text' => 'caravan(III)']],
        [['callback_data' => 'caravan_dodge_2000', 'text' => 'caravan(IV)']],
        [['callback_data' => 'dakota_dodge_1997', 'text' => 'dakota(II)']],
        [['callback_data' => 'durango_dodge_1998', 'text' => 'durango(I)']],
        [['callback_data' => 'intrepid_dodge_1997', 'text' => 'intrepid(II)']],
        [['callback_data' => 'neon_dodge_1999', 'text' => 'neon(II)']],
        [['callback_data' => 'ram_dodge_1994', 'text' => 'ram(II)(BR/BE)']],
        [['callback_data' => 'ramcharger_dodge_1999', 'text' => 'ramcharger(III)']],
        [['callback_data' => 'stratus_dodge_1995', 'text' => 'stratus(I)']],
        [['callback_data' => 'stratus_dodge_2000', 'text' => 'stratus(II)']],
        [['callback_data' => 'viper_dodge_1995', 'text' => 'viper(II)']]
        ],
    'dodge_2001' => [
        [['callback_data' => 'caravan_dodge_2000', 'text' => 'caravan(IV)']],
        [['callback_data' => 'dakota_dodge_1997', 'text' => 'dakota(II)']],
        [['callback_data' => 'durango_dodge_1998', 'text' => 'durango(I)']],
        [['callback_data' => 'intrepid_dodge_1997', 'text' => 'intrepid(II)']],
        [['callback_data' => 'neon_dodge_1999', 'text' => 'neon(II)']],
        [['callback_data' => 'ram_dodge_1994', 'text' => 'ram(II)(BR/BE)']],
        [['callback_data' => 'ram_dodge_2001', 'text' => 'ram(III)(DR/DH)']],
        [['callback_data' => 'ramcharger_dodge_1999', 'text' => 'ramcharger(III)']],
        [['callback_data' => 'stratus_dodge_2000', 'text' => 'stratus(II)']],
        [['callback_data' => 'viper_dodge_1995', 'text' => 'viper(II)']]
        ],
    'dodge_2002' => [
        [['callback_data' => 'caravan_dodge_2000', 'text' => 'caravan(IV)']],
        [['callback_data' => 'dakota_dodge_1997', 'text' => 'dakota(II)']],
        [['callback_data' => 'durango_dodge_1998', 'text' => 'durango(I)']],
        [['callback_data' => 'intrepid_dodge_1997', 'text' => 'intrepid(II)']],
        [['callback_data' => 'neon_dodge_1999', 'text' => 'neon(II)']],
        [['callback_data' => 'ram_dodge_2001', 'text' => 'ram(III)(DR/DH)']],
        [['callback_data' => 'stratus_dodge_2000', 'text' => 'stratus(II)']],
        [['callback_data' => 'viper_dodge_1995', 'text' => 'viper(II)']],
        [['callback_data' => 'viper_dodge_2002', 'text' => 'viper(III)']]
        ],
    'dodge_2003' => [
        [['callback_data' => 'caravan_dodge_2000', 'text' => 'caravan(IV)']],
        [['callback_data' => 'dakota_dodge_1997', 'text' => 'dakota(II)']],
        [['callback_data' => 'durango_dodge_1998', 'text' => 'durango(I)']],
        [['callback_data' => 'durango_dodge_2003', 'text' => 'durango(II)']],
        [['callback_data' => 'intrepid_dodge_1997', 'text' => 'intrepid(II)']],
        [['callback_data' => 'magnum_dodge_2003', 'text' => 'magnum(I)']],
        [['callback_data' => 'neon_dodge_1999', 'text' => 'neon(II)']],
        [['callback_data' => 'ram_dodge_2001', 'text' => 'ram(III)(DR/DH)']],
        [['callback_data' => 'stratus_dodge_2000', 'text' => 'stratus(II)']],
        [['callback_data' => 'viper_dodge_2002', 'text' => 'viper(III)']]
        ],
    'dodge_2004' => [
        [['callback_data' => 'caravan_dodge_2000', 'text' => 'caravan(IV)']],
        [['callback_data' => 'dakota_dodge_1997', 'text' => 'dakota(II)']],
        [['callback_data' => 'dakota_dodge_2004', 'text' => 'dakota(III)']],
        [['callback_data' => 'durango_dodge_2003', 'text' => 'durango(II)']],
        [['callback_data' => 'intrepid_dodge_1997', 'text' => 'intrepid(II)']],
        [['callback_data' => 'magnum_dodge_2003', 'text' => 'magnum(I)']],
        [['callback_data' => 'neon_dodge_1999', 'text' => 'neon(II)']],
        [['callback_data' => 'ram_dodge_2001', 'text' => 'ram(III)(DR/DH)']],
        [['callback_data' => 'stratus_dodge_2000', 'text' => 'stratus(II)']],
        [['callback_data' => 'viper_dodge_2002', 'text' => 'viper(III)']]
        ],
    'dodge_2005' => [
        [['callback_data' => 'caravan_dodge_2000', 'text' => 'caravan(IV)']],
        [['callback_data' => 'charger_dodge_2005', 'text' => 'charger(V)(LX)']],
        [['callback_data' => 'dakota_dodge_2004', 'text' => 'dakota(III)']],
        [['callback_data' => 'durango_dodge_2003', 'text' => 'durango(II)']],
        [['callback_data' => 'magnum_dodge_2003', 'text' => 'magnum(I)']],
        [['callback_data' => 'neon_dodge_1999', 'text' => 'neon(II)']],
        [['callback_data' => 'ram_dodge_2001', 'text' => 'ram(III)(DR/DH)']],
        [['callback_data' => 'stratus_dodge_2000', 'text' => 'stratus(II)']],
        [['callback_data' => 'viper_dodge_2002', 'text' => 'viper(III)']]
        ],
    'dodge_2006' => [
        [['callback_data' => 'caliber_dodge_2006', 'text' => 'caliber(I)']],
        [['callback_data' => 'caravan_dodge_2000', 'text' => 'caravan(IV)']],
        [['callback_data' => 'charger_dodge_2005', 'text' => 'charger(V)(LX)']],
        [['callback_data' => 'dakota_dodge_2004', 'text' => 'dakota(III)']],
        [['callback_data' => 'durango_dodge_2003', 'text' => 'durango(II)']],
        [['callback_data' => 'magnum_dodge_2003', 'text' => 'magnum(I)']],
        [['callback_data' => 'nitro_dodge_2006', 'text' => 'nitro']],
        [['callback_data' => 'ram_dodge_2001', 'text' => 'ram(III)(DR/DH)']],
        [['callback_data' => 'stratus_dodge_2000', 'text' => 'stratus(II)']],
        [['callback_data' => 'viper_dodge_2002', 'text' => 'viper(III)']]
        ],
    'dodge_2007' => [
        [['callback_data' => 'avenger_dodge_2007', 'text' => 'avenger(II)']],
        [['callback_data' => 'caliber_dodge_2006', 'text' => 'caliber(I)']],
        [['callback_data' => 'caravan_dodge_2000', 'text' => 'caravan(IV)']],
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'charger_dodge_2005', 'text' => 'charger(V)(LX)']],
        [['callback_data' => 'dakota_dodge_2004', 'text' => 'dakota(III)']],
        [['callback_data' => 'durango_dodge_2003', 'text' => 'durango(II)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'magnum_dodge_2003', 'text' => 'magnum(I)']],
        [['callback_data' => 'nitro_dodge_2006', 'text' => 'nitro']],
        [['callback_data' => 'ram_dodge_2001', 'text' => 'ram(III)(DR/DH)']],
        [['callback_data' => 'viper_dodge_2002', 'text' => 'viper(III)']],
        [['callback_data' => 'viper_dodge_2007', 'text' => 'viper(IV)']]
        ],
    'dodge_2008' => [
        [['callback_data' => 'avenger_dodge_2007', 'text' => 'avenger(II)']],
        [['callback_data' => 'caliber_dodge_2006', 'text' => 'caliber(I)']],
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'challenger_dodge_2008', 'text' => 'challenger(III)']],
        [['callback_data' => 'charger_dodge_2005', 'text' => 'charger(V)(LX)']],
        [['callback_data' => 'dakota_dodge_2004', 'text' => 'dakota(III)']],
        [['callback_data' => 'durango_dodge_2003', 'text' => 'durango(II)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'magnum_dodge_2003', 'text' => 'magnum(I)']],
        [['callback_data' => 'nitro_dodge_2006', 'text' => 'nitro']],
        [['callback_data' => 'ram_dodge_2001', 'text' => 'ram(III)(DR/DH)']],
        [['callback_data' => 'ram_dodge_2008', 'text' => 'ram(IV)(DS/DJ)']],
        [['callback_data' => 'viper_dodge_2007', 'text' => 'viper(IV)']]
        ],
    'dodge_2009' => [
        [['callback_data' => 'avenger_dodge_2007', 'text' => 'avenger(II)']],
        [['callback_data' => 'caliber_dodge_2006', 'text' => 'caliber(I)']],
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'challenger_dodge_2008', 'text' => 'challenger(III)']],
        [['callback_data' => 'charger_dodge_2005', 'text' => 'charger(V)(LX)']],
        [['callback_data' => 'dakota_dodge_2004', 'text' => 'dakota(III)']],
        [['callback_data' => 'durango_dodge_2003', 'text' => 'durango(II)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'nitro_dodge_2006', 'text' => 'nitro']],
        [['callback_data' => 'ram_dodge_2008', 'text' => 'ram(IV)(DS/DJ)']],
        [['callback_data' => 'viper_dodge_2007', 'text' => 'viper(IV)']]
        ],
    'dodge_2010' => [
        [['callback_data' => 'avenger_dodge_2007', 'text' => 'avenger(II)']],
        [['callback_data' => 'caliber_dodge_2006', 'text' => 'caliber(I)']],
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'challenger_dodge_2008', 'text' => 'challenger(III)']],
        [['callback_data' => 'charger_dodge_2005', 'text' => 'charger(V)(LX)']],
        [['callback_data' => 'charger_dodge_2010', 'text' => 'charger(VI)(LD)']],
        [['callback_data' => 'dakota_dodge_2004', 'text' => 'dakota(III)']],
        [['callback_data' => 'durango_dodge_2010', 'text' => 'durango(III)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'nitro_dodge_2006', 'text' => 'nitro']],
        [['callback_data' => 'ram_dodge_2008', 'text' => 'ram(IV)(DS/DJ)']],
        [['callback_data' => 'viper_dodge_2007', 'text' => 'viper(IV)']]
        ],
    'dodge_2011' => [
        [['callback_data' => 'avenger_dodge_2007', 'text' => 'avenger(II)']],
        [['callback_data' => 'caliber_dodge_2006', 'text' => 'caliber(I)']],
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'challenger_dodge_2008', 'text' => 'challenger(III)']],
        [['callback_data' => 'charger_dodge_2010', 'text' => 'charger(VI)(LD)']],
        [['callback_data' => 'dakota_dodge_2004', 'text' => 'dakota(III)']],
        [['callback_data' => 'durango_dodge_2010', 'text' => 'durango(III)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'nitro_dodge_2006', 'text' => 'nitro']],
        [['callback_data' => 'ram_dodge_2008', 'text' => 'ram(IV)(DS/DJ)']]
        ],
    'dodge_2012' => [
        [['callback_data' => 'avenger_dodge_2007', 'text' => 'avenger(II)']],
        [['callback_data' => 'caliber_dodge_2006', 'text' => 'caliber(I)']],
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'challenger_dodge_2008', 'text' => 'challenger(III)']],
        [['callback_data' => 'charger_dodge_2010', 'text' => 'charger(VI)(LD)']],
        [['callback_data' => 'dart_dodge_2012', 'text' => 'dart']],
        [['callback_data' => 'durango_dodge_2010', 'text' => 'durango(III)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'ram_dodge_2008', 'text' => 'ram(IV)(DS/DJ)']],
        [['callback_data' => 'viper_dodge_2012', 'text' => 'viper(V)']]
        ],
    'dodge_2013' => [
        [['callback_data' => 'avenger_dodge_2007', 'text' => 'avenger(II)']],
        [['callback_data' => 'caliber_dodge_2006', 'text' => 'caliber(I)']],
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'challenger_dodge_2008', 'text' => 'challenger(III)']],
        [['callback_data' => 'charger_dodge_2010', 'text' => 'charger(VI)(LD)']],
        [['callback_data' => 'dart_dodge_2012', 'text' => 'dart']],
        [['callback_data' => 'durango_dodge_2010', 'text' => 'durango(III)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'ram_dodge_2008', 'text' => 'ram(IV)(DS/DJ)']],
        [['callback_data' => 'viper_dodge_2012', 'text' => 'viper(V)']]
        ],
    'dodge_2014' => [
        [['callback_data' => 'avenger_dodge_2007', 'text' => 'avenger(II)']],
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'challenger_dodge_2008', 'text' => 'challenger(III)']],
        [['callback_data' => 'charger_dodge_2010', 'text' => 'charger(VI)(LD)']],
        [['callback_data' => 'dart_dodge_2012', 'text' => 'dart']],
        [['callback_data' => 'durango_dodge_2010', 'text' => 'durango(III)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'ram_dodge_2008', 'text' => 'ram(IV)(DS/DJ)']],
        [['callback_data' => 'viper_dodge_2012', 'text' => 'viper(V)']]
        ],
    'dodge_2015' => [
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'challenger_dodge_2008', 'text' => 'challenger(III)']],
        [['callback_data' => 'charger_dodge_2010', 'text' => 'charger(VI)(LD)']],
        [['callback_data' => 'dart_dodge_2012', 'text' => 'dart']],
        [['callback_data' => 'durango_dodge_2010', 'text' => 'durango(III)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'ram_dodge_2008', 'text' => 'ram(IV)(DS/DJ)']],
        [['callback_data' => 'viper_dodge_2012', 'text' => 'viper(V)']]
        ],
    'dodge_2016' => [
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'challenger_dodge_2008', 'text' => 'challenger(III)']],
        [['callback_data' => 'charger_dodge_2010', 'text' => 'charger(VI)(LD)']],
        [['callback_data' => 'dart_dodge_2012', 'text' => 'dart']],
        [['callback_data' => 'durango_dodge_2010', 'text' => 'durango(III)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'ram_dodge_2008', 'text' => 'ram(IV)(DS/DJ)']],
        [['callback_data' => 'viper_dodge_2012', 'text' => 'viper(V)']]
        ],
    'dodge_2017' => [
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'challenger_dodge_2008', 'text' => 'challenger(III)']],
        [['callback_data' => 'charger_dodge_2010', 'text' => 'charger(VI)(LD)']],
        [['callback_data' => 'durango_dodge_2010', 'text' => 'durango(III)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'ram_dodge_2008', 'text' => 'ram(IV)(DS/DJ)']],
        [['callback_data' => 'viper_dodge_2012', 'text' => 'viper(V)']]
        ],
    'dodge_2018' => [
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'challenger_dodge_2008', 'text' => 'challenger(III)']],
        [['callback_data' => 'charger_dodge_2010', 'text' => 'charger(VI)(LD)']],
        [['callback_data' => 'durango_dodge_2010', 'text' => 'durango(III)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'ram_dodge_2008', 'text' => 'ram(IV)(DS/DJ)']],
        [['callback_data' => 'ram_dodge_2018', 'text' => 'ram(V)']]
        ],
    'dodge_2019' => [
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'challenger_dodge_2008', 'text' => 'challenger(III)']],
        [['callback_data' => 'charger_dodge_2010', 'text' => 'charger(VI)(LD)']],
        [['callback_data' => 'durango_dodge_2010', 'text' => 'durango(III)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'ram_dodge_2008', 'text' => 'ram(IV)(DS/DJ)']],
        [['callback_data' => 'ram_dodge_2018', 'text' => 'ram(V)']]
        ],
    'dodge_2020' => [
        [['callback_data' => 'caravan_dodge_2007', 'text' => 'caravan(V)']],
        [['callback_data' => 'challenger_dodge_2008', 'text' => 'challenger(III)']],
        [['callback_data' => 'charger_dodge_2010', 'text' => 'charger(VI)(LD)']],
        [['callback_data' => 'durango_dodge_2010', 'text' => 'durango(III)']],
        [['callback_data' => 'journey_dodge_2007', 'text' => 'journey(I)']],
        [['callback_data' => 'ram_dodge_2018', 'text' => 'ram(V)']]
    ],
    ];